fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    apt: git://github.com/puppetlabs/puppetlabs-apt.git
    zypprepo: https://github.com/deadpoint/puppet-zypprepo.git
  symlinks:
    elasticsearch: "#{source_dir}"
